apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-mongo-depl
spec:
  selector:
    matchLabels:
      app: ticket-mongo
  template:
    metadata:
      labels:
        app: ticket-mongo
    spec:
      containers:
        - name: ticket-mongo
          image: mongo
          env:
            - name: redis_url
              value: redis://ticket-redis-srv:6379
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-mongo-service
spec:
  selector:
    app: ticket-mongo
  ports:
  - port: 27017
    targetPort: 27017